### ISSUE TITLE
rgb_preview.py returns module depthai.node has no attribute 'XLinkOut' on Depthai 3.0.0rc2

### ISSUE THREAD

**Issue by pd3a** [luxonis/depthai-core#1374]
I'm on depthai version 3.0.0rc2. When I run rgb_preview.py it returns there is no attribute 'XLinkOut'. 

I used to run this on previous version of depthai 2.29 and it runs perfectly without any issue. After updating to 3.0.0rc2 there are some syntaxes changed like set resolution, setfps, XLinkOut. There is no proper documentation available for depthai 3.0.0rc2.

**Comment by lnotspotl** [comment]
The `rgb_preview.py` example has been replaced with the [camera_output.py](https://github.com/luxonis/depthai-core/blob/main/examples/python/Camera/camera_output.py) example in `depthai-v3`. Could you take a look at that and see whether that example works for you? Also, there have been several breaking changes introduced to `depthai-v3` and so it's expected that some of the `v2` examples won't work. Take a look at our [porting guide](https://github.com/luxonis/depthai-core/blob/main/V2V3PortinGuide.md) for a brief summary of the breaking changes and how `v2` differs from `v3`
